# Generated by Django 2.2.6 on 2022-05-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.utilits


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220424_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(validators=[posts.utilits.validate_not_empty], verbose_name='Текст поста'),
        ),
    ]
